# -*- coding: utf-8 -*-
"""data-cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUbDwwN3ApX_XUbWb8ApbtUPmXgsNmoL
"""

import pandas as pd

"""

---


**Get file data**"""

from google.colab import userdata
file_path = userdata.get('data_file_path')

df = pd.read_excel(file_path)
df

"""

---


**Remove Duplicates**"""

df = df.drop_duplicates()
df

"""

---

**Remove not useful columns**"""

df = df.drop(columns='Not_Useful_Column')
df

"""

---

**Cleaning Last Name Column**"""

df['Last_Name'] = df['Last_Name'].str.strip(r'[/..._]')
df

"""

---

**Reformat Phone Number Column**"""

df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '', regex=True)
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: f'{x[0:3]}-{x[3:6]}-{x[6:10]}')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na--', '', regex=True)
df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '', regex=True)

df

"""

---

**Split Address Column**"""

df[['Street_Address', 'State_Address', 'Zip_Code']] = df['Address'].str.split(',',n=2,expand=True)
df

"""

---

**Reformat Paying Costumer and Do Not Contact columns**"""

df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N')
df

"""

---

**Clean Null values**"""

df = df.replace('N/a', '')
df = df.fillna('')
df

"""

---

**Filter Rows Data**"""

for x in df.index:
  if df.loc[x, 'Do_Not_Contact'] == 'Y':
    df.drop(x, inplace=True)
df

for x in df.index:
  if df.loc[x, 'Phone_Number'] == '':
    df.drop(x, inplace=True)
df

df = df.reset_index(drop=True)
df

